name: "New Issue"
description: Create a new ticket for a new request
labels: [
  "NewIssue"
]
body:
  - type: markdown
    attributes:
      value: "Please add a short descriptive title to describe the issue above."
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the issue
      placeholder: Describe in a few lines your issue or request
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Use Case"
      description: Indicate here some basic examples of your issue.
      placeholder: A few specific words about your issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Optional: Please apply any labels or types as necessary - leave blank for unknown."
