active: true
derived: false
header: ''
level: 1.0
links: []
normative: true
ref: ''
requirement-level: 2
reviewed: null
text: NOS shall have a simulation environment which is configurable in its startup location, time, and configuration or state of the vehicle
