name: Build

on: 
  push:
  pull_request:

jobs:
    fsw:
      runs-on: ubuntu-latest
      container:
        image: ivvitc/nos3-64:20241010
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: config
          run: make config  
        - name: build directory
          run: mkdir ./fsw/build
        - name: build
          run: make build-test
        - name: test
          run: make test-fsw

    sim:
      runs-on: ubuntu-latest
      container:
        image: ivvitc/nos3-64:20241010
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: config
          run: make config  
        - name: build directory
          run: mkdir ./sims/build
        - name: build
          run: make build-sim
