name: Build

on: 
  pull_request:

jobs:
    fsw:
      runs-on: ubuntu-latest
      container:
        image: ivvitc/nos3-64:20241010
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Update
          run: apt-get update
        - name: Install dependencies
          run: apt-get install -y python3 docker docker.io
        - name: prep
          run: make prep
        - name: config
          run: make config  
        - name: build
          run: make build-fsw

    sim:
      runs-on: ubuntu-latest
      container:
        image: ivvitc/nos3-64:20241010
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Update
          run: apt-get update
        - name: Install dependencies
          run: apt-get install -y python3 docker docker.io
        - name: prep
          run: make prep
        - name: config
          run: make config  
        - name: build
          run: make build-sim
